// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj0YMpOKR_XCxoLej7QUpgHFWdqkiWJQs',
    appId: '1:1018807673580:web:dcfdf0a019331f2e8ebbc9',
    messagingSenderId: '1018807673580',
    projectId: 'musicplayerflutter-69302',
    authDomain: 'musicplayerflutter-69302.firebaseapp.com',
    storageBucket: 'musicplayerflutter-69302.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1xEPMjXsygIWb9qxi81BADT6AX-hM5jg',
    appId: '1:1018807673580:android:6900a30fcf79dd998ebbc9',
    messagingSenderId: '1018807673580',
    projectId: 'musicplayerflutter-69302',
    storageBucket: 'musicplayerflutter-69302.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaQbdcgSt0eFsBNXtOE9bs1-nTNxCdKqM',
    appId: '1:1018807673580:ios:d610f74dcf14b3128ebbc9',
    messagingSenderId: '1018807673580',
    projectId: 'musicplayerflutter-69302',
    storageBucket: 'musicplayerflutter-69302.firebasestorage.app',
    iosBundleId: 'com.example.musicolie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaQbdcgSt0eFsBNXtOE9bs1-nTNxCdKqM',
    appId: '1:1018807673580:ios:d610f74dcf14b3128ebbc9',
    messagingSenderId: '1018807673580',
    projectId: 'musicplayerflutter-69302',
    storageBucket: 'musicplayerflutter-69302.firebasestorage.app',
    iosBundleId: 'com.example.musicolie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCj0YMpOKR_XCxoLej7QUpgHFWdqkiWJQs',
    appId: '1:1018807673580:web:e81e02e9756d59088ebbc9',
    messagingSenderId: '1018807673580',
    projectId: 'musicplayerflutter-69302',
    authDomain: 'musicplayerflutter-69302.firebaseapp.com',
    storageBucket: 'musicplayerflutter-69302.firebasestorage.app',
  );
}
